-- Auto-generated by matugen. Do not edit manually.
-- Require this file to get matugen colors in Hyprland Lua config.

return {
<* for name, value in colors *>
  {{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
  image = "{{image}}",
}