# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e9e1db"

# Title color for boxes
theme[title]="#e3c28c"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d6c4aa"

# Background color of selected item in processes box
theme[selected_bg]="#e3c28c"

# Foreground color of selected item in processes box
theme[selected_fg]="#412d05"

# Color of inactive/disabled text
theme[inactive_fg]="#d0c5b6"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c0cc99"

# Cpu box outline color
theme[cpu_box]="#998f82"

# Memory/disks box outline color
theme[mem_box]="#998f82"

# Net up/down box outline color
theme[net_box]="#998f82"

# Processes box outline color
theme[proc_box]="#998f82"

# Box divider line and small boxes line color
theme[div_line]="#4d463b"

# Temperature graph colors
theme[temp_start]="#d6c4aa"
theme[temp_mid]="#e3c28c"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d6c4aa"
theme[cpu_mid]="#e3c28c"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d6c4aa"
theme[free_mid]=""
theme[free_end]="#514531"

# Mem/Disk cached meter
theme[cached_start]="#c0cc99"
theme[cached_mid]=""
theme[cached_end]="#636e43"

# Mem/Disk available meter
theme[available_start]="#e3c28c"
theme[available_mid]=""
theme[available_end]="#7f6538"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#d6c4aa"
theme[download_mid]="#e3c28c"
theme[download_end]="#c0cc99"

# Upload graph colors
theme[upload_start]="#d6c4aa"
theme[upload_mid]="#e3c28c"
theme[upload_end]="#c0cc99"