# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e5e2e0"

# Title color for boxes
theme[title]="#ffffff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c8c6c2"

# Background color of selected item in processes box
theme[selected_bg]="#ffffff"

# Foreground color of selected item in processes box
theme[selected_fg]="#2f312b"

# Color of inactive/disabled text
theme[inactive_fg]="#c7c7bf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ffffff"

# Cpu box outline color
theme[cpu_box]="#91918a"

# Memory/disks box outline color
theme[mem_box]="#91918a"

# Net up/down box outline color
theme[net_box]="#91918a"

# Processes box outline color
theme[proc_box]="#91918a"

# Box divider line and small boxes line color
theme[div_line]="#464741"

# Temperature graph colors
theme[temp_start]="#c8c6c2"
theme[temp_mid]="#ffffff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c8c6c2"
theme[cpu_mid]="#ffffff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c8c6c2"
theme[free_mid]=""
theme[free_end]="#474743"

# Mem/Disk cached meter
theme[cached_start]="#ffffff"
theme[cached_mid]=""
theme[cached_end]="#ebdfe4"

# Mem/Disk available meter
theme[available_start]="#ffffff"
theme[available_mid]=""
theme[available_end]="#e3e3d9"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c8c6c2"
theme[download_mid]="#ffffff"
theme[download_end]="#ffffff"

# Upload graph colors
theme[upload_start]="#c8c6c2"
theme[upload_mid]="#ffffff"
theme[upload_end]="#ffffff"