#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                                    



# Image Path
$image = /home/pseudo/Wallpapers/Canopy/slender girls.jpg

# All Colors

$background = rgba(f0fdf2ff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(e7f4eaff)

$inverse_primary = rgba(00e29eff)

$inverse_surface = rgba(28332cff)

$on_background = rgba(131e18ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(002114ff)

$on_primary_fixed = rgba(002114ff)

$on_primary_fixed_variant = rgba(005236ff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(00201aff)

$on_secondary_fixed = rgba(00201aff)

$on_secondary_fixed_variant = rgba(224e45ff)

$on_surface = rgba(131e18ff)

$on_surface_variant = rgba(3e4942ff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(00201fff)

$on_tertiary_fixed = rgba(00201fff)

$on_tertiary_fixed_variant = rgba(00504eff)

$outline = rgba(6e7a72ff)

$outline_variant = rgba(bdcac0ff)

$primary = rgba(006c4aff)

$primary_container = rgba(46ffb8ff)

$primary_fixed = rgba(46ffb8ff)

$primary_fixed_dim = rgba(00e29eff)

$scrim = rgba(000000ff)

$secondary = rgba(3a665cff)

$secondary_container = rgba(bdecdfff)

$secondary_fixed = rgba(bdecdfff)

$secondary_fixed_dim = rgba(a2d0c3ff)

$shadow = rgba(000000ff)

$source_color = rgba(6ad5a4ff)

$surface = rgba(f0fdf2ff)

$surface_bright = rgba(f0fdf2ff)

$surface_container = rgba(e4f1e7ff)

$surface_container_high = rgba(deebe1ff)

$surface_container_highest = rgba(d9e6dcff)

$surface_container_low = rgba(eaf7edff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(d0ddd3ff)

$surface_tint = rgba(006c4aff)

$surface_variant = rgba(d9e6dcff)

$tertiary = rgba(1a6967ff)

$tertiary_container = rgba(a8efedff)

$tertiary_fixed = rgba(a8efedff)

$tertiary_fixed_dim = rgba(8cd3d1ff)
