#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                                    



# Image Path
$image = Null

# All Colors

$background = rgba(fff8f4ff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(ffeedfff)

$inverse_primary = rgba(ffb964ff)

$inverse_surface = rgba(3a2e21ff)

$on_background = rgba(241a0eff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(2b1700ff)

$on_primary_fixed = rgba(2b1700ff)

$on_primary_fixed_variant = rgba(663e00ff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(281900ff)

$on_secondary_fixed = rgba(281900ff)

$on_secondary_fixed_variant = rgba(5a4319ff)

$on_surface = rgba(241a0eff)

$on_surface_variant = rgba(524436ff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(251a00ff)

$on_tertiary_fixed = rgba(251a00ff)

$on_tertiary_fixed_variant = rgba(594401ff)

$outline = rgba(857464ff)

$outline_variant = rgba(d7c3b0ff)

$primary = rgba(875300ff)

$primary_container = rgba(ffddbaff)

$primary_fixed = rgba(ffddbaff)

$primary_fixed_dim = rgba(ffb964ff)

$scrim = rgba(000000ff)

$secondary = rgba(745a2fff)

$secondary_container = rgba(ffdeadff)

$secondary_fixed = rgba(ffdeadff)

$secondary_fixed_dim = rgba(e4c18dff)

$shadow = rgba(000000ff)

$source_color = rgba(d5bba1ff)

$surface = rgba(fff8f4ff)

$surface_bright = rgba(fff8f4ff)

$surface_container = rgba(ffead8ff)

$surface_container_high = rgba(fae5d1ff)

$surface_container_highest = rgba(f4dfcbff)

$surface_container_low = rgba(fff1e6ff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(ebd7c3ff)

$surface_tint = rgba(875300ff)

$surface_variant = rgba(f4dfcbff)

$tertiary = rgba(735b1aff)

$tertiary_container = rgba(ffdf96ff)

$tertiary_fixed = rgba(ffdf96ff)

$tertiary_fixed_dim = rgba(e3c377ff)
