#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                                    



# Image Path
$image = /home/pseudo/Wallpapers/Canopy/wallhaven-7p8783.jpg

# All Colors

$background = rgba(fff8f6ff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(ffede9ff)

$inverse_primary = rgba(ffb4a4ff)

$inverse_surface = rgba(3d2c29ff)

$on_background = rgba(271815ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(3e0500ff)

$on_primary_fixed = rgba(3e0500ff)

$on_primary_fixed_variant = rgba(8d1700ff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(311302ff)

$on_secondary_fixed = rgba(311302ff)

$on_secondary_fixed_variant = rgba(643d26ff)

$on_surface = rgba(271815ff)

$on_surface_variant = rgba(55423eff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(2c1600ff)

$on_tertiary_fixed = rgba(2c1600ff)

$on_tertiary_fixed_variant = rgba(663e0aff)

$outline = rgba(89726dff)

$outline_variant = rgba(dcc1bbff)

$primary = rgba(b82100ff)

$primary_container = rgba(ffdad3ff)

$primary_fixed = rgba(ffdad3ff)

$primary_fixed_dim = rgba(ffb4a4ff)

$scrim = rgba(000000ff)

$secondary = rgba(7f543bff)

$secondary_container = rgba(ffdbc9ff)

$secondary_fixed = rgba(ffdbc9ff)

$secondary_fixed_dim = rgba(f3ba9bff)

$shadow = rgba(000000ff)

$source_color = rgba(774034ff)

$surface = rgba(fff8f6ff)

$surface_bright = rgba(fff8f6ff)

$surface_container = rgba(ffe9e5ff)

$surface_container_high = rgba(ffe2dcff)

$surface_container_highest = rgba(f9dcd6ff)

$surface_container_low = rgba(fff0eeff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(f0d4ceff)

$surface_tint = rgba(b82100ff)

$surface_variant = rgba(f9dcd6ff)

$tertiary = rgba(815521ff)

$tertiary_container = rgba(ffdcbdff)

$tertiary_fixed = rgba(ffdcbdff)

$tertiary_fixed_dim = rgba(f6bb7eff)
