#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = e8e2d5
subtext            = ccc6b5
main               = 15130c
main-elevated      = 3b3930
main-transition    = 100e07
highlight          = 1d1c13
highlight-elevated = 37352c
sidebar            = 15130c
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = e8e2d5
button             = d6c871
button-active      = f3e489
button-disabled    = d6c871
tab-active         = 15130c
notification       = a7d0b6
notification-error = ffb4ab
misc               = 000000
play-button        = cfc7a2
play-button-active = ebe3bd
progress-fg        = d6c871
progress-bg        = 15130c
heart              = ffb4ab
pagelink-active    = c3ecd2
radio-btn-active   = c3ecd2