#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = e0e2ef
subtext            = c4c6d3
main               = 10131c
main-elevated      = 363943
main-transition    = 0b0e17
highlight          = 181b25
highlight-elevated = 32343f
sidebar            = 10131c
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = e0e2ef
button             = b3c5ff
button-active      = dae2ff
button-disabled    = b3c5ff
tab-active         = 10131c
notification       = d0bdf6
notification-error = ffb4ab
misc               = 000000
play-button        = c4c3ea
play-button-active = e2dfff
progress-fg        = b3c5ff
progress-bg        = 10131c
heart              = ffb4ab
pagelink-active    = eaddff
radio-btn-active   = eaddff