#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = eee0d4
subtext            = d4c4b5
main               = 18120c
main-elevated      = 403830
main-transition    = 130d07
highlight          = 211a13
highlight-elevated = 3b332b
sidebar            = 18120c
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = eee0d4
button             = f8bb71
button-active      = ffddb8
button-disabled    = f8bb71
tab-active         = 18120c
notification       = bbcd9e
notification-error = ffb4ab
misc               = 000000
play-button        = dfc2a2
play-button-active = fcddbd
progress-fg        = f8bb71
progress-bg        = 18120c
heart              = ffb4ab
pagelink-active    = d7e9b8
radio-btn-active   = d7e9b8