# --- System Daemons & Services ---
exec-once = uwsm app -- awww-daemon                         # Wallpaper daemon
exec-once = hyprpm reload -n                    # Reload plugins (with notification)
exec-once = uwsm app -- hyprsunset              # Blue light filter
exec-once = ollama serve 
exec-once = uwsm app -- swaync

# --- Scripts & Automation ---
#exec-once = ~/.config/Scripts/hide-waydroid-apps.sh
#exec-once = archer-inject.sh
#exec-once = ~/.config/hypr/scripts/mako-config
exec-once = archer-earbuds-status
exec-once = archer-battery-monitor

# --- Multimedia & Aesthetics ---
# Delay ensures Pipewire is fully initialized before playing
#exec-once = sleep 1 && paplay ~/.config/hypr/assets/sounds/TempleOS-Hymn-Risen.wav

exec-once = easyeffects --gapplication-service  # EasyEffects DSP