# --- System Daemons & Services ---
exec-once = ollama serve 
#exec-once = qs -c ii
exec-once = archer-earbuds-status
exec-once = easyeffects --gapplication-service  # EasyEffects DSP



# --- Scripts & Automation ---
#exec-once = archer-inject.sh
#exec-once = ~/.config/hypr/scripts/mako-config

#exec-once = archer-battery-monitor

# --- Multimedia & Aesthetics ---
# Delay ensures Pipewire is fully initialized before playing
#exec-once = sleep 1 && paplay ~/.config/hypr/assets/sounds/TempleOS-Hymn-Risen.wav

