# === UI ===
bindd = SUPER ALT, RETURN, Tmux,         exec, uwsm-app -- xdg-terminal-exec --dir="$(cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER,     B,      Waybar,        exec, ~/.config/waybar/assets/scripts/toggle_waybar
bindd = SUPER,     Delete, Logout,        exec, hyprctl dispatch exit 0
bindd = SUPER,     SPACE,  Launcher,      exec, rofi -show drun -theme ~/.config/rofi/launchers/type-1/style-5.rasi
#bindd = ALT,       SPACE,  Theme menu,    exec, menu theme

# === Apps ===
bindd = SUPER SHIFT, M, Music,     exec, launch-or-focus spotify
bindd = SUPER SHIFT, D, Docker,    exec, launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal,    exec, launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian,  exec, launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora,    exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# === Web ===
bindd = SUPER SHIFT, A, ChatGPT,   exec, launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, C, Calendar,  exec, launch-webapp "https://app.hey.com/calendar/weeks/"
bindd = SUPER SHIFT, E, Email,     exec, launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube,   exec, launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, X, X,         exec, launch-webapp "https://x.com/"
bindd = SUPER SHIFT, P, Photos,    exec, launch-or-focus-webapp "Google Photos" "https://photos.google.com/"

bindd = SUPER SHIFT ALT,  A, Grok,      exec, launch-webapp "https://grok.com"
bindd = SUPER SHIFT ALT,  G, WhatsApp,  exec, launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT ALT,  X, X Post,    exec, launch-webapp "https://x.com/compose/post"
bindd = SUPER SHIFT CTRL, G, Messages,  exec, launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"

# === Tools ===
bindd = ALT, M,      Toolbox,       exec, archer-hub
bindd = ALT, X,      Study,         exec, ghostty --class=Yazi --title=Yazi -e timeout 30s yazi "~/Videos/Anime"
bindd = ALT, C,      Music Player,  exec, [float; center] ghostty --title=rmpc -e rmpc
#bindd = ALT, B,      Wallpaper,     exec, archer-switch-walls
bindd = ALT, B, Set wallpaper,        exec, archer-set-bg
bindd = ALT, SPACE, Select theme,     exec, archer-set-theme
bindd = ALT, comma,  Unmount,       exec, archer-hdd-unmount
bindd = ALT, Z,      Dictation,     exec, voxtype record toggle

# === Special Keys ===
bindd  = , XF86NotificationCenter, WhatsApp, exec, launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd  = , XF86Favorites, Calibre, exec, launch-or-focus calibre "uwsm-app -- calibre"

# === Hardware ===
bindd = SUPER, Q, Wifi QR,              exec, ghostty --class=WifiQR --title=WifiQR -e archer-wifi-qr
bindd = SUPER, M, Comic (Latin),        exec, archer-comic-translate lat
bindd = SUPER, N, Comic (Asian),        exec, archer-comic-translate cjk

# === Deprecated ===
#bindd = ALT, M, Media downloader,     exec, [float; size 70% 70%; center] alacritty -e archer-media-download
#bindd = ALT, M, Media downloader,     exec, [float; size 70% 70%; center] ghostty -e archer-media-download
#bind  = SUPER, grave, scrolloverview:overview, toggle
bindd = SUPER, grave, Overview,       hyprexpo:expo, toggle