# === UI ===
#bindd = SUPER, grave, Overview,  hyprexpo:expo, toggle
bindd = SUPER  ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER, B, Waybar, exec, ~/.config/waybar/assets/scripts/waybar-theme
bindd = SUPER, SPACE, Applications launcher, exec, rofi-applications

# === Apps ===
bindd = SUPER SHIFT, M, Music,     exec, launch-or-focus spotify
bindd = SUPER SHIFT, D, Docker,    exec, launch-tui lazydocker
bindd = SUPER SHIFT, S, Signal,    exec, launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian,  exec, launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora,    exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# === Tools ===
bindd = ALT, M,      Toolbox,       exec, archer-hub
bindd = ALT, B, Set wallpaper,        exec, rofi-set-bg
bindd = ALT, SPACE, Select theme,     exec, rofi-set-theme
bindd = ALT, comma,  Unmount,       exec, archer-hdd-unmount
bindd = ALT, Z,      Dictation,     exec, voxtype record toggle

# === Special Keys ===
bindd  = , XF86NotificationCenter, WhatsApp, exec, launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd  = , XF86Favorites, Calibre, exec, launch-or-focus calibre "uwsm-app -- calibre"

# === Hardware ===
bindd = SUPER, M, Comic (Latin),        exec, archer-comic-translate lat
bindd = SUPER, N, Comic (Asian),        exec, archer-comic-translate cjk

# === Deprecated ===
bind  = SUPER, grave, scrolloverview:overview, toggle

bindd = SUPER  ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = ALT, C,  Music Player, exec, [float; center] kitty --title=rmpc -e rmpc
bindd = ALT, X, Study, exec, [float; size 700 200; center] kitty --class=Yazi --title=Yazi -e timeout 30s yazi "~/Videos/Anime"
bindd = SUPER, Q, Wifi QR, exec, [float; size 302 416; move 967 40; pin] kitty --class=wifi-qr --title=wifi-qr -e archer-wifi-qr