general {
    lock_cmd = system-lock                               # lock screen and 1password[cite: 6]
    before_sleep_cmd = ARCHER_LOCK_ONLY=true system-lock # lock before suspend without scheduling display off.[cite: 6]
    after_sleep_cmd = sleep 1 && system-wake            # delay for PAM readiness, then turn on display.[cite: 6]
    inhibit_sleep = 3                                           # wait until screen is locked[cite: 6]
}

# Start screensaver after 2.5 minutes
#listener {
 #   timeout = 150
  #  on-timeout = pidof hyprlock || launch-screensaver
#}

# Lock system after 5 minutes
listener {
    timeout = 152
    on-timeout = system-lock
    on-resume = system-wake
}