background = 0xFF1E1E2E
base = 0xFF252538
text = 0xFFC6D0F5
alternate_base = 0xFF414559
bright_text = 0xFFE6E9EF
accent = 0xFFCA9EE6
secondary_accent = 0xFFF4B8E4

font_family = Inter
font_mono_family = JetBrains Mono
font_size_h1 = 18
font_size_h2 = 15
font_size_regular = 11

icon_theme = Papirus-Dark
