general {
    lock_cmd = system-lock
    before_sleep_cmd = LOCK_ONLY=true system-lock && sleep 1
    after_sleep_cmd = sleep 1 && system-wake
    inhibit_sleep = 5
}

# Start screensaver after 2.5 minutes
# listener {
#     timeout = 150
#     on-timeout = pidof hyprlock || omarchy-launch-screensaver
# }

# Lock system after 5 minutes
listener {
    timeout = 300
    on-timeout = system-lock
    on-resume = system-wake
}