source = ~/.config/hypr/bin/hyprland.conf

# ── General ────────────────────────────────────────────────────────────────────

general {
    layout              = master
    gaps_in             = 2
    gaps_out            = 2
    border_size         = 1
    col.active_border   = $primary $tertiary 45deg 
    col.inactive_border = $surface_container_high
}

# ── Decoration ─────────────────────────────────────────────────────────────────

decoration {
    rounding           = 6
    active_opacity     = 0.92
    inactive_opacity   = 0.95
    #fullscreen_opacity = 0.92

    blur {
        enabled           = true
        size              = 4
        passes            = 3
        contrast          = 0.95
        brightness        = 0.9
        vibrancy          = 0.15
        vibrancy_darkness = 0.25
        noise             = 0.015
        ignore_opacity    = true
    }
}