source = ~/.config/hypr/scripts/Plugins/barcol.css
#source = ~/.config/hypr/hyprexpo-binds.conf

# Toggle overview
#bind = SUPER, grave, hyprexpo:expo, toggle

# ── Hyprland Plugin Configuration ─────────────────────────────────────────────

plugin {

 hyprexpo {
        columns = 3
        gaps_in = 5                     # Changed from gap_size
        gaps_out = 5                    # Added for outer grid padding
        gesture_distance = 100
        bg_col = rgba(1e2233cc) 
        workspace_method = center current
        
        # Configurable key to exit the overview (Optional)
        cancel_key = escape
    }

    #scrolloverview {
       # gesture_distance = 300 
        #scale = 0.75             # Closer to the video's layout
        #workspace_gap = 50       # Tighter grid
       # wallpaper = 2            
       # blur = true 
       # active_only = false    # If this is true, it hides empty workspaces
       # auto_fill = true       
       # draw_active_workspace_only = false      

    #}

    hyprfocus {
        enabled                  = true
        mode                     = slide   # flash | shrink
        slide_height             = 5
        keyboard_focus_animation = slide
        mouse_focus_animation    = slide
    }

    hyprbars {
        # Visuals
        bar_height                = 29
        bar_color                 = $bg1
        bar_blur                  = true
        bar_part_of_window        = true
        bar_precedence_over_border = true

        # Typography
        bar_title_enabled         = false
        bar_text_size             = 11
        bar_text_font             = "SF Pro Display Semibold"
        bar_text_align            = center
        col.text                  = $fg

        # Layout
        bar_buttons_alignment     = left
        bar_padding               = 12
        bar_button_padding        = 8
        icon_on_hover             = true

        # Buttons — [COLOR], [SIZE], [ICON], [ACTION]
        hyprbars-button = $red,    15, , hyprctl dispatch killactive
        hyprbars-button = $yellow, 15, , ~/.config/hypr/scripts/Plugins/hyprbars-minimize.sh
        hyprbars-button = $green,  15, , hyprctl dispatch togglefloating

        on_double_click = hyprctl dispatch fullscreen 1
    }

}