[Interface]
# Key for Japan
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = kD/Yyr79voLJY6DcNY6Ct10avIloN8VKDNni6fZhV2Q=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# JP-FREE#27
PublicKey = dew7bKQjobIKkIaSvkDNM9vpl1ZFZ6EwIOJM4jhZd28=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 212.102.51.115:51820

PersistentKeepalive = 25