[Interface]
# Key for Poland
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = gAz/HHCvYUOy77W6iMC8+5IS+NSTulpdSwnt6nl16VM=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# PL-FREE#2
PublicKey = tw0rM/g0IiZKM+Hz0T7jJTSDk8aiOgGEUuG6NkR2mik=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 217.138.209.18:51820

PersistentKeepalive = 25