[Interface]
# Key for Singapore
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 4P6AR56ERUwmhmWuswo290INtx//YYpy+PnT1Tn/BmI=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SG-FREE#19
PublicKey = DU0jJf1tLDu9Nr84tFt1Eph27zsvI3Gu5dkwTGyE9Wk=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 103.216.221.73:51820

PersistentKeepalive = 25