#hyprexpo_gesture = 3, up, expo
hyprexpo-gesture = 3, vertical, expo
#scrolloverview-gesture = 3, vertical, overview

# Native gestures for horizontal movement
gesture = 3, horizontal, workspace
gesture = 4, up, scale: 1.5, fullscreen
gesture = 4, down, scale: 0.5, fullscreen