# --- Main Colors ---
background            #12140f
foreground            #e2e3da
cursor                #e2e3da
cursor_text_color     #12140f

selection_background  #3e4e32
selection_foreground  #d7eac5

url_color             #78d7c2

# --- ANSI Colors ---
color0                #12140f
color1                #ffb4ab
color2                #78d7c2
color3                #bacca9
color4                #a7d388
color5                #78d7c2
color6                #bacca9
color7                #e2e3da

color8                #43493d
color9                #93000a
color10               #53b4a0
color11               #3e4e32
color12               #86b069
color13               #3c4b30
color14               #005144
color15               #c3c9b9

# --- Starship Prompt Bubbles ---
color255              #86b069
color254              #a7d388
color253              #3e4e32
color252              #bacca9
color251              #53b4a0
color250              #78d7c2
color249              #93000a
color248              #ffb4ab

color232              #081e00
color233              #153800
color234              #d7eac5
color235              #26351b
color236              #001d18
color237              #00382f
color238              #ffdad6
color239              #690005
color240              #081e00

# Matched with unthemed light/dark
color243              #a7d388
color244              #ffb4ab
color245              #43493d

# --- UI Elements ---
active_tab_foreground   #153800
active_tab_background   #a7d388
inactive_tab_foreground #081e00
inactive_tab_background #86b069

active_border_color     #a7d388
inactive_border_color   #8d9385

# --- Marks ---
mark1_foreground        #0a2100
mark1_background        #c3f0a2
mark2_foreground        #111f08
mark2_background        #d6e9c3
mark3_foreground        #00201a
mark3_background        #94f4de