# --- Main Colors ---
background            #1b1015
foreground            #f3dde4
cursor                #f3dde4
cursor_text_color     #1b1015

selection_background  #773557
selection_foreground  #ffe0eb

url_color             #ffb4a8

# --- ANSI Colors ---
color0                #1b1015
color1                #ffb4ab
color2                #ffb4a8
color3                #ffafd3
color4                #ffafd3
color5                #ffb4a8
color6                #ffafd3
color7                #f3dde4

color8                #56414a
color9                #93000a
color10               #a62519
color11               #773557
color12               #a2196e
color13               #713052
color14               #8e120a
color15               #dcbfca

# --- Starship Prompt Bubbles ---
color255              #a2196e
color254              #ffafd3
color253              #773557
color252              #ffafd3
color251              #a62519
color250              #ffb4a8
color249              #93000a
color248              #ffb4ab

color232              #fffbff
color233              #620040
color234              #ffe0eb
color235              #56193b
color236              #fffbff
color237              #690000
color238              #ffdad6
color239              #690005
color240              #fffbff

# Matched with unthemed light/dark
color243              #ffafd3
color244              #ffb4ab
color245              #56414a

# --- UI Elements ---
active_tab_foreground   #620040
active_tab_background   #ffafd3
inactive_tab_foreground #fffbff
inactive_tab_background #a2196e

active_border_color     #ffafd3
inactive_border_color   #a48a94

# --- Marks ---
mark1_foreground        #3d0026
mark1_background        #ffd8e7
mark2_foreground        #3b0325
mark2_background        #ffd8e7
mark3_foreground        #410000
mark3_background        #ffdad4