# --- Main Colors ---
background            #18120c
foreground            #ede0d5
cursor                #ede0d5
cursor_text_color     #18120c

selection_background  #5d411d
selection_foreground  #ffdab1

url_color             #d8e679

# --- ANSI Colors ---
color0                #18120c
color1                #ffb4ab
color2                #d8e679
color3                #e8bf91
color4                #ffd7ab
color5                #c1cf64
color6                #e8bf91
color7                #ede0d5

color8                #524436
color9                #93000a
color10               #bcca60
color11               #5d411d
color12               #feb351
color13               #5d411d
color14               #434b00
color15               #d6c3b1

# --- Starship Prompt Bubbles ---
color255              #feb351
color254              #ffd7ab
color253              #5d411d
color252              #e8bf91
color251              #bcca60
color250              #d8e679
color249              #93000a
color248              #ffb4ab

color232              #4b2c00
color233              #472a00
color234              #ffdab1
color235              #442b09
color236              #303600
color237              #2d3400
color238              #ffdad6
color239              #690005
color240              #4b2c00

# Matched with unthemed light/dark
color243              #ffd7ab
color244              #ffb4ab
color245              #524436

# --- UI Elements ---
active_tab_foreground   #472a00
active_tab_background   #ffd7ab
inactive_tab_foreground #4b2c00
inactive_tab_background #feb351

active_border_color     #ffd7ab
inactive_border_color   #9f8e7d

# --- Marks ---
mark1_foreground        #2a1700
mark1_background        #ffddb8
mark2_foreground        #2a1700
mark2_background        #ffddb8
mark3_foreground        #191e00
mark3_background        #ddeb7d