#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗

[config]
version_check = false

# ─── Templates ────────────────────────────────────────────────────────────────

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/bin/hyprland.conf"
post_hook = "hyprctl reload"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock.conf"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/matugen.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/CSS/matugen.css"
post_hook = "swaync-client -rs"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.cache/matugen/rofi.rasi"

[templates.cava]
input_path = "~/.config/matugen/templates/cava.ini"
output_path = "~/.config/cava/themes/matugen-theme"

[templates.rmpc]
input_path = "~/.config/matugen/templates/rmpc.ron"
output_path = "~/.config/rmpc/themes/matugen.ron"

[templates.spicetify]
input_path = "~/.config/matugen/templates/spicetify.ini"
output_path = "~/.config/spicetify/Themes/Comfy/color.ini"
post_hook = "spicetify apply -n"