#!/usr/bin/env python3
import subprocess, json, sys, os, tempfile

# ── matugen color loader ───────────────────────────────────────────────────────
# reads from ~/.cache/matugen/colors.json (generated by switch_walls.sh)
# uses base16 keys from matugen's --json hex output

def load_matugen_colors():
    cache    = os.path.expanduser("~/.cache/matugen/colors.json")
    fallback = [
        '#b7bdf8',  # lavender
        '#c6a0f6',  # mauve
        '#f5bde6',  # pink
        '#91d7e3',  # sky
        '#8bd5ca',  # teal
        '#8aadf4',  # blue
    ]
    try:
        with open(cache) as f:
            data = json.load(f)
        b    = data["base16"]
        mode = "dark"
        return [
            b["base0D"][mode]["color"],  # blue   / primary
            b["base0E"][mode]["color"],  # purple / secondary
            b["base0F"][mode]["color"],  # pink   / tertiary
            b["base0C"][mode]["color"],  # cyan   / sky
            b["base0B"][mode]["color"],  # green  / teal
            b["base09"][mode]["color"],  # orange / accent
        ]
    except Exception:
        return fallback

GRADIENT_COLORS = load_matugen_colors()

# ── bar characters ─────────────────────────────────────────────────────────────
BARS            = "⣀⣄⣤⣦⣶⣷⣿"
ASCII_MAX_RANGE = 7

# ── cava config ────────────────────────────────────────────────────────────────
CAVA_CONFIG = """
[general]
bars = 8
framerate = 60
sensitivity = 100

[input]
method = pipewire

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7
"""

# ── pango frame generator ──────────────────────────────────────────────────────
def generate_pango(line, frame_count):
    bars_data = line.strip().split(';')
    if not bars_data:
        return None

    pango_output = ""
    for i, bar_str in enumerate(bars_data):
        try:
            val   = int(bar_str)
            char  = BARS[0] if val == 0 else BARS[min(val, len(BARS) - 1)]
            color = GRADIENT_COLORS[(i + (frame_count // 10)) % len(GRADIENT_COLORS)]
            pango_output += f'<span foreground="{color}">{char}</span>'
        except (ValueError, IndexError):
            continue

    return pango_output

# ── main loop ──────────────────────────────────────────────────────────────────
def run_cava():
    with tempfile.NamedTemporaryFile(mode='w+', delete=False, suffix='.conf') as f:
        f.write(CAVA_CONFIG)
        temp_path = f.name

    process                 = None
    frame_count             = 0
    silent_frames_threshold = 90   # 1.5 s at 60 fps
    silent_frames_count     = 0

    try:
        process = subprocess.Popen(
            ['cava', '-p', temp_path],
            stdout=subprocess.PIPE, text=True, bufsize=1
        )

        for line in process.stdout:
            frame_count += 1
            pango_text   = generate_pango(line, frame_count)

            is_silent = all(v == '0' for v in line.strip().split(';') if v)

            if is_silent:
                silent_frames_count += 1
            else:
                silent_frames_count = 0

            if silent_frames_count >= silent_frames_threshold:
                print(json.dumps({"text": ""}))
            else:
                print(json.dumps({"text": pango_text}))

            sys.stdout.flush()

    except Exception:
        print(json.dumps({"text": ""}))
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)
        if process:
            process.kill()

if __name__ == "__main__":
    run_cava()