sensors:
  - hwmon: /sys/class/hwmon
    name: coretemp
    indices: [1, 2, 3, 4, 5]

  - hwmon: /sys/class/hwmon
    name: nvme
    indices: [1]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0,  0,  42]
  - [1,  40, 48]
  - [2,  45, 54]
  - [3,  50, 60]
  - [4,  55, 66]
  - [5,  62, 72]
  - [6,  68, 78]
  - [7,  75, 32767]
