#!/usr/bin/env bash
# =============================================================================
# hardware/battery-monitor.sh — TLP configuration + battery monitor service
# Tailored for ThinkPad T14 Gen 2i (SMP BAT0, natacpi driver)
#
# What this does:
#   1. Writes a TLP config optimized for T14 Gen 2i
#   2. Sets charge thresholds via natacpi (extends battery lifespan)
#   3. Lets user pick a power profile (powersave/balanced/performance)
#   4. Enables battery-monitor.timer for low battery notifications
#   5. Enables tlp-rdw for automatic profile switching on AC/BAT
# =============================================================================

set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/../lib/helpers.sh"

section "TLP Battery Configuration (ThinkPad T14 Gen 2i)"

# ─── Guard — only run on battery systems ──────────────────────────────────────
if ! has_battery; then
    warn "No battery detected — skipping battery configuration"
    exit 0
fi

# ─── Check TLP is installed ───────────────────────────────────────────────────
if ! command -v tlp &>/dev/null; then
    warn "TLP not installed — skipping"
    exit 0
fi

# ─── Write TLP config ─────────────────────────────────────────────────────────
msg "Writing TLP configuration for ThinkPad T14 Gen 2i..."

sudo tee /etc/tlp.conf > /dev/null << 'TLPCONF'
# =============================================================================
# TLP Configuration — ThinkPad T14 Gen 2i (20W1S6EY00)
# Generated by Archer install/hardware/battery-monitor.sh
# =============================================================================

# ─── General ──────────────────────────────────────────────────────────────────
TLP_ENABLE=1
TLP_DEFAULT_MODE=AC
TLP_PERSISTENT_DEFAULT=0

# ─── Power Profiles ───────────────────────────────────────────────────────────
# AC = plugged in, BAT = on battery
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave

CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0

# ─── Intel CPU (Tiger Lake i5) ────────────────────────────────────────────────
CPU_MIN_PERF_ON_AC=0
CPU_MAX_PERF_ON_AC=100
CPU_MIN_PERF_ON_BAT=0
CPU_MAX_PERF_ON_BAT=40

# ─── Platform Profile (ThinkPad) ──────────────────────────────────────────────
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=low-power

# ─── Battery Care (natacpi — ThinkPad specific) ───────────────────────────────
# Thresholds extend battery lifespan significantly
# START: begin charging when below this %
# STOP:  stop charging when above this %
# Recommendation for daily use with frequent plugging:
#   Conservative longevity: START=40 STOP=80
#   Balanced:               START=20 STOP=80
#   Maximum capacity:       START=0  STOP=100 (defeats the purpose)
START_CHARGE_THRESH_BAT0=40
STOP_CHARGE_THRESH_BAT0=80

# ─── WiFi ─────────────────────────────────────────────────────────────────────
WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on

# ─── USB Autosuspend ──────────────────────────────────────────────────────────
USB_AUTOSUSPEND=1
# Exclude USB devices from autosuspend if needed (add IDs)
# USB_EXCLUDE_VENDOR_ID=""

# ─── PCIe / ASPM ──────────────────────────────────────────────────────────────
PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersupersave

# ─── Runtime Power Management ─────────────────────────────────────────────────
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=on

# ─── Disk ─────────────────────────────────────────────────────────────────────
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=60

# ─── Sound ────────────────────────────────────────────────────────────────────
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
TLPCONF

ok "TLP config written to /etc/tlp.conf"

# ─── Power profile selection ──────────────────────────────────────────────────
section "Power Profile Selection"
msg "This sets your default TLP platform profile:"
msg "  powersave   — quiet, cool, max battery life"
msg "  balanced    — recommended for daily use"
msg "  performance — full CPU power, more heat/consumption"
echo ""

PROFILE=$(gum choose --cursor "▶ " \
    --selected.foreground 82 \
    "balanced" "powersave" "performance")

ok "Selected profile: $PROFILE"

# ─── Apply TLP ────────────────────────────────────────────────────────────────
section "Applying TLP"

sudo tlp start && ok "TLP started" || warn "TLP start failed — will apply on reboot"

# Apply selected profile
case "$PROFILE" in
    powersave)
        sudo tlp bat 2>/dev/null && ok "Forced battery/powersave mode" || true
        ;;
    performance)
        sudo tlp ac 2>/dev/null && ok "Forced AC/performance mode" || true
        ;;
    balanced|*)
        ok "Balanced mode — TLP will auto-switch on AC/BAT"
        ;;
esac

# ─── Apply charge thresholds immediately ──────────────────────────────────────
section "Charge Thresholds"

if [[ -f /sys/class/power_supply/BAT0/charge_control_start_threshold ]]; then
    echo 40 | sudo tee /sys/class/power_supply/BAT0/charge_control_start_threshold > /dev/null
    echo 80 | sudo tee /sys/class/power_supply/BAT0/charge_control_end_threshold   > /dev/null
    ok "Charge thresholds applied: start=40% stop=80%"
    ok "Battery longevity mode active — charging stops at 80%"
else
    warn "Could not apply charge thresholds directly — TLP will handle on next boot"
fi

# ─── Enable services ──────────────────────────────────────────────────────────
section "Enabling Services"

enable_system_service tlp.service
enable_system_service tlp-rdw.service 2>/dev/null || true  # optional, handles AC/BAT switching

systemctl --user daemon-reload
enable_user_service battery-monitor.timer

# ─── Summary ──────────────────────────────────────────────────────────────────
section "Battery Configuration Summary"
ok "TLP configured for ThinkPad T14 Gen 2i"
ok "Profile selected: $PROFILE"
ok "Charge thresholds: 40% → 80% (battery longevity)"
ok "CPU max on battery: 40% (saves power)"
ok "WiFi powersave: off on AC, on on battery"
if is_enabled_user battery-monitor.timer 2>/dev/null; then
    ok "battery-monitor.timer: enabled (low battery notifications)"
else
    warn "battery-monitor.timer: not enabled (service file not deployed yet)"
fi
warn "Reboot recommended for all TLP settings to fully apply"
