plugin {
    scrolloverview {
        gesture_distance = 300 
        scale = 0.75             # Closer to the video's layout
        workspace_gap = 50       # Tighter grid
        wallpaper = 2            
        blur = true 
        active_only = false    # If this is true, it hides empty workspaces
        auto_fill = true       
        draw_active_workspace_only = false      

        shadow {
            enabled = true       
            range = 30           # Slightly tighter shadow for better definition
            render_power = 4     
            color = rgba(00000088)
        }
    }

        hyprexpo {
        columns = 3
        gap_size = 5
        gesture_distance = 100
        bg_col = rgba(1e2233cc) 
        inactive_col = rgb(2a2a33)
        active_col = rgb(3a3a44)
        border_col = rgb(ff8700)
        border_size = 3
        animation_duration = 200
        animation_fps = 60 
        workspace_method = center current
        hyprexpo-gesture = 3, vertical, expo
        skip_empty = true
        
    }
}

# Force workspaces 1 through 5 to always exist
#workspace = 1, persistent:true
#workspace = 2, persistent:true
#workspace = 3, persistent:true
#workspace = 4, persistent:true
#workspace = 5, persistent:true
#workspace = 6, persistent:true