# Copy / Paste
bindd = SUPER, C, Universal copy, sendshortcut, CTRL, Insert, activewindow
bindd = SUPER, V, Universal paste, sendshortcut, SHIFT, Insert, activewindow
bindd = SUPER, X, Universal cut, sendshortcut, CTRL, X, activewindow
#bindd = SUPER CTRL, V, Clipboard manager, exec, launch-walker -m clipboard
bindd = SUPER CTRL, V, Clipboard manager, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = CTRL, D, exec, cliphist list | rofi -dmenu | cliphist delete
bindd = SUPER, period, Emoji, exec, rofimoji