# === Web ===
bindd = SUPER SHIFT, A, Claude,   exec,  launch-webapp "https://claude.ai"
bindd = SUPER SHIFT, C, Calendar,  exec, launch-webapp "https://app.hey.com/calendar/weeks/"
#bindd = SUPER SHIFT, E, Email,     exec, launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube,   exec, launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, X, X,         exec, launch-webapp "https://x.com/"
bindd = SUPER SHIFT, P, Photos,    exec, launch-or-focus-webapp "Google Photos" "https://photos.google.com/"

bindd = SUPER SHIFT ALT,  A, Grok,      exec, launch-webapp "https://grok.com"
bindd = SUPER SHIFT ALT,  G, WhatsApp,  exec, launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT ALT,  X, X Post,    exec, launch-webapp "https://x.com/compose/post"
bindd = SUPER SHIFT CTRL, G, Messages,  exec, launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
